spring:
  application:
    name: eureka-server
  boot:
    admin:
      context-path: /admin
  config:
    import: configserver
server:
  port: ${EUREKA_PORT}
eureka:
  instance:
    hostname: ${HOST_NAME}
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 5

---
spring:
  profiles: peer1
eureka:
  instance:
    hostname: peer1

---
spring:
  profiles: peer2
eureka:
  instance:
    hostname: peer2

---
spring:
  profiles: peer3
eureka:
  instance:
    hostname: peer3

management:
  endpoints:
    web:
      exposure:
        include: "*"
   
